# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish to Elastic Beanstalk

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Generate deployment package
        working-directory: ./
        run: zip -r deploy.zip * .ebextensions .platform -x "**node_modules**"

      - name: Beanstalk Deploy for app
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: "wallet-ui"
          environment_name: "wallet-ui-a"
          region: "us-west-2"
          version_label: "ui-service-a-${{ github.sha }}"
          deployment_package: ./deploy.zip
          use_existing_version_if_available: true

      - name: Deployed!
        run: echo App deployed to ELB
